HANPUM-PJT/HANPUM-PJT

backend/src/main/java/backend/hanpum/exception/exception/test/TestNotFoundException.java
backend/src/main/java/backend/hanpum/exception/format/code/ApiResponse.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

[BE]Feat: 예외처리 아웃라인 및 가이드 추가

---

frontend/src/components/BottomTab.styled.tsx
frontend/src/components/BottomTab.tsx

- 바텀 탭 네비게이션 추가
- 정확한 디자인이 정해지지 않아  색상과 이미지 등은 임의로 할당. 추 후 수정예정입니다.

[FE] Feat: 바텀 탭 추가

---

backend/src/main/java/backend/hanpum/domain/course/entity/Attraction.java
backend/src/main/java/backend/hanpum/domain/course/entity/Course.java
backend/src/main/java/backend/hanpum/domain/course/entity/CourseDay.java
backend/src/main/java/backend/hanpum/domain/course/entity/CourseDayId.java
backend/src/main/java/backend/hanpum/domain/course/entity/CourseType.java
backend/src/main/java/backend/hanpum/domain/course/entity/Review.java
backend/src/main/java/backend/hanpum/domain/course/entity/Waypoint.java

[BE]경로 관련 엔티티추가

---

backend/src/main/java/backend/hanpum/domain/course/entity/Course.java
backend/src/main/java/backend/hanpum/domain/course/entity/Review.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/domain/member/enums/Gender.java
backend/src/main/java/backend/hanpum/domain/member/enums/MemberType.java
backend/src/main/java/backend/hanpum/domain/schedule/entity/Schedule.java

- [✔️] feature 병합
- Member 엔티티 추가
- "Course", "Review", "Schedule" 엔티티에 Member 엔티티와 관련된 연관관계 코드 주석 해제
- [✔️] 커밋 컨벤션에 맞게 작성했습니다.
- [✔️] 변경 사항에 대한 테스트를 완료했습니다. (빌드/버그수정/기능에 대한 테스트)

[BE]멤버 관련 엔티티 추가 및 수정

---

frontend/src/assets/icons/index.ts
frontend/src/assets/icons/nextArrow.svg
frontend/src/components/common/Icon/Icon.tsx
frontend/src/pages/LoginPage.tsx
frontend/src/types/svg.d.ts
frontend/tsconfig.json

- svg icon을 컴포넌트로 꺼내와서 어느 곳에서든 컴포넌트로 사용할 수 있게 만듦
- svg 파일을 assets의 icons 폴더에 넣고 icons폴더 안에 있는 index.ts에 이름을 명시
- 그 후 원하는 곳에서 `<Icon name="IconNext" size={20}/>` 이렇게 불러와서 사용

[FE] icon 공통컴포넌트 개발 완료

---

backend/src/main/java/backend/hanpum/config/WebConfig.java
backend/src/main/java/backend/hanpum/domain/test/TestController.java

- [v] test 코드 작성
- [BE] 통신 테스트용 코드, 설정 추가

[BE] 통신 테스트용 코드, 설정 추가

---

frontend/src/App.tsx
frontend/src/global/GlobalStyle.tsx
frontend/src/global/theme.ts
frontend/src/pages/Router.tsx

- App.tsx에 있는 Router를 Router.tsx 파일을 생성해 App.tsx에서 import 해올 수 있게 수정
- global 폴더를 생성해 GlobalStyle.tsx를 생성해 reset css와 기타 전역적으로 사용하는 css 수정 및 생성
- theme.ts파일을 생성해 주로 사용하게 되는 색상, 배경색, 폰트 등을 저장해 뽑아쓰기 위해 생성

[FE] Router 및 Global file 생성, 수정

---

backend/src/main/java/backend/hanpum/config/SwaggerConfig.java
backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/AttractionResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseDayResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseDetailResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/GetCourseDayResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/WayPointResDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/Course.java
backend/src/main/java/backend/hanpum/domain/course/entity/CourseDay.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseRepository.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/exception/exception/course/CourseNotFoundException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- [v] 코드 개선
- 일부 엔티티 수정했습니다.
- 코스 상세 조회 API 작성.
- 코스 일차정보 조회 API 작성.

[BE] 경로 상세/일차 조회 API 작성

---

backend/build.gradle
backend/src/main/java/backend/hanpum/config/RedisConfig.java
backend/src/main/java/backend/hanpum/config/SwaggerConfig.java
backend/src/main/java/backend/hanpum/domain/auth/controller/AuthController.java
backend/src/main/java/backend/hanpum/domain/auth/dto/CheckEmailAuthCodeReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/SendEmailAuthCodeReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthService.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/repository/MemberRepository.java
backend/src/main/java/backend/hanpum/exception/exception/auth/AuthenticationCodeInvalidException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/AuthenticationMailSendFailedException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/AuthenticationMailTimeoutException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/EmailDuplicatedException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- Redis 의존성 추가 및 설정 파일 추가
- 스웨거 설정 파일에 인증 API 추가
- 이메일 중복 검사 및 인증번호 전송 API 코드 작성
- 이메일 인증 API 코드 작성

[BE]이메일 중복 검사 및 인증 API 작성

---

backend/build.gradle
backend/src/main/java/backend/hanpum/config/SecurityConfig.java
backend/src/main/java/backend/hanpum/domain/auth/controller/AuthController.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/CheckEmailAuthCodeReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/CheckLoginIdDuplicationReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/CheckNicknameDuplicationReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/SendEmailAuthCodeReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/SignUpReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthService.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/repository/MemberRepository.java
backend/src/main/java/backend/hanpum/exception/exception/auth/EmailExpiredException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/EmailNotAuthenticatedException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/LoginIdDuplicatedException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/LoginIdExpiredException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/NicknameDuplicatedException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/NicknameExpiredException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- 아이디 중복검사 API 코드 작성
- 닉네임 중복검사 API 코드 작성
- 회원가입 API 코드 작성
- 스프링 시큐리티 의존성 추가
- 스프링 시큐리티 설정 파일 생성

[BE]회원가입 API 작성

---

backend/src/main/java/backend/hanpum/domain/schedule/controller/ScheduleController.java
backend/src/main/java/backend/hanpum/domain/schedule/dto/requestDto/SchedulePostReqDto.java
backend/src/main/java/backend/hanpum/domain/schedule/dto/requestDto/ScheduleRunReqDto.java
backend/src/main/java/backend/hanpum/domain/schedule/entity/Schedule.java
backend/src/main/java/backend/hanpum/domain/schedule/service/ScheduleService.java
backend/src/main/java/backend/hanpum/domain/schedule/service/ScheduleServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

[BE] Schedule API 구조

---

backend/src/main/java/backend/hanpum/domain/course/entity/CourseDay.java
backend/src/main/java/backend/hanpum/domain/course/entity/Waypoint.java
backend/src/main/java/backend/hanpum/domain/schedule/controller/ScheduleController.java
backend/src/main/java/backend/hanpum/domain/schedule/dto/requestDto/ScheduleDayReqDto.java
backend/src/main/java/backend/hanpum/domain/schedule/dto/requestDto/ScheduleStartReqDto.java
backend/src/main/java/backend/hanpum/domain/schedule/dto/responseDto/ScheduleDayResDto.java
backend/src/main/java/backend/hanpum/domain/schedule/dto/responseDto/ScheduleWayPointResDto.java
backend/src/main/java/backend/hanpum/domain/schedule/entity/Memo.java
backend/src/main/java/backend/hanpum/domain/schedule/entity/Schedule.java
backend/src/main/java/backend/hanpum/domain/schedule/entity/ScheduleDay.java
backend/src/main/java/backend/hanpum/domain/schedule/entity/ScheduleWayPoint.java
backend/src/main/java/backend/hanpum/domain/schedule/repository/ScheduleDayRepository.java
backend/src/main/java/backend/hanpum/domain/schedule/repository/custom/ScheduleRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/schedule/repository/custom/ScheduleRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/schedule/service/ScheduleService.java
backend/src/main/java/backend/hanpum/domain/schedule/service/ScheduleServiceImpl.java
backend/src/main/java/backend/hanpum/exception/exception/schedule/ScheduleDayNotFoundException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- [v] 코드 개선
일차별 일정 조회, 국토 대장정 시 진행중인지 휴식중인지 구분할 수 있는 진행상태 전환 로직 구현

[BE] 일차별 일정 조회, 진행상태 전환 로직 구현

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseReviewResDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/Review.java
backend/src/main/java/backend/hanpum/domain/course/repository/ReviewRepository.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/exception/course/CourseReviewsNotFoundException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

[BE]경로리뷰 조회 API

---

backend/src/main/java/backend/hanpum/exception/exception/course/CourseDayNotFoundException.java
backend/src/main/java/backend/hanpum/exception/exception/course/CourseNotFoundException.java
backend/src/main/java/backend/hanpum/exception/exception/course/CourseReviewsNotFoundException.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- 핸들러에 등록안된 예외처리들 추가.
- 일부 예외처리 수정

[BE]예외처리 수정/추가

---

frontend/src/components/Style/Route/RouteAddMainPage.styled.tsx
frontend/src/pages/Route/RouteAddMainPage.tsx
frontend/src/pages/Route/RouteAddPlacePage.tsx

[FE] 경로 기본설정 페이지 공개여부 스위치 버튼 추가

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/CourseReviewReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseReviewResDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/Review.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseRepository.java
backend/src/main/java/backend/hanpum/domain/course/repository/ReviewRepository.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 리뷰등록 api 추가
- 리뷰수정 api 추가
- 리뷰삭제 api 추가
- 삭제는 테스트 해보지 못했습니다.

[BE] 리뷰 등록/수정/삭제 api

---

backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java

[BE] ErrorCode enum 파일 수정

---

backend/src/main/java/backend/hanpum/config/SwaggerConfig.java
backend/src/main/java/backend/hanpum/domain/group/controller/GroupController.java
backend/src/main/java/backend/hanpum/domain/group/dto/requestDto/GroupPostReqDto.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupPostResDto.java
backend/src/main/java/backend/hanpum/domain/group/entity/Group.java
backend/src/main/java/backend/hanpum/domain/group/entity/GroupMember.java
backend/src/main/java/backend/hanpum/domain/group/enums/JoinType.java
backend/src/main/java/backend/hanpum/domain/group/repository/GroupMemberRepository.java
backend/src/main/java/backend/hanpum/domain/group/repository/GroupRepository.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/exception/exception/group/GroupAlreadyJoinedException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

[BE] 모임 생성 API 작성

---

backend/src/main/java/backend/hanpum/config/redis/RedisDao.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java

- 기존 회원 가입 로직에 사용되던 redis CRUD 코드를 redisDao 클래스로 이전

[BE] redis CRUD 코드 수정

---

backend/src/main/java/backend/hanpum/config/SwaggerConfig.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/controller/MemberController.java
backend/src/main/java/backend/hanpum/domain/member/dto/requestDto/UpdateMemberInfoReqDto.java
backend/src/main/java/backend/hanpum/domain/member/dto/requestDto/UpdateNicknameReqDto.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberService.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 닉네임 변경 API 코드 작성
- 회원 기본 정보(이름, 생일, 성별, 전화번호) 수정 API 코드 작성

[BE] 회원 정보 수정 API 

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/AttractionReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/CourseDayReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/MakeCourseReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/WayPointReqDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/CourseDay.java
backend/src/main/java/backend/hanpum/domain/course/repository/AttractionRepository.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseDayRepository.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseTypeRepository.java
backend/src/main/java/backend/hanpum/domain/course/repository/WaypointRepository.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/domain/schedule/repository/custom/ScheduleRepositoryImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 경로 생성 API 추가
- 엔티티 일부 수정, 레포

[BE] 경로생성 API

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseRepository.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- [v] 기타(아래에 자세한 내용 기입해주세요)
- 경로삭제 api 
- 컨트롤러 단 서비스 호출이 주석 처리되어 있는데, 따로 멤버ID 변수를 넣어 테스트해 봤습니다.

[BE] 경로삭제 api

---

backend/src/main/java/backend/hanpum/domain/auth/controller/AuthController.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/FindMemberLoginIdReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/FindMemberPasswordReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/responseDto/FindMemberLoginIdResDto.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthService.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/domain/member/repository/MemberRepository.java
backend/src/main/java/backend/hanpum/exception/exception/auth/MemberNotFoundException.java
backend/src/main/java/backend/hanpum/exception/exception/auth/TemporaryPasswordMailSendFailedException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- 로그인 아이디 찾기 API 코드 작성
- 비밀번호 찾기 (임시 비밀번호 발급) API 코드 작성

[BE] 회원 로그인 정보 찾기 API

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/EditCourseReqDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/Attraction.java
backend/src/main/java/backend/hanpum/domain/course/entity/Course.java
backend/src/main/java/backend/hanpum/domain/course/entity/CourseDay.java
backend/src/main/java/backend/hanpum/domain/course/entity/Waypoint.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseTypeRepository.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

[BE] 경로수정 API 추가

---

backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseResDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/Course.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java

- [v] 코드 개선
- 디자인 변경에 따른 코드조회 API 수정
- [V] 커밋 컨벤션에 맞게 작성했습니다.
- [V] 변경 사항에 대한 테스트를 완료했습니다. (빌드/버그수정/기능에 대한 테스트)

[BE] 경로조회시 출발지, 도착지, 총거리 추가

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java

- [v] 코드 개선
- [v] 기타(아래에 자세한 내용 기입해주세요)
- 경로목록조회 API에 페이징 및 정렬 기능을 추가하였습니다.
- 정렬 중 인기많은 순의 경우 기준이 모호하여 현재 (평균평점 * 리뷰수)로 처리하였습니다. 추후, 조회수가 추가되거나 하면 가중치를 주어 보완하겠습니다.

[BE] 조회 API 페이징, 정렬 추가

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/CourseReviewResDto.java
backend/src/main/java/backend/hanpum/domain/course/repository/ReviewRepository.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java

- [v] 코드 개선
- 리뷰목록조회 API 페이징/정렬 추가

[BE] 리뷰목록조회 페이징/정렬 추가

---

backend/src/main/java/backend/hanpum/domain/group/controller/GroupController.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupApplyListGetResDto.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupApplyResDto.java
backend/src/main/java/backend/hanpum/domain/group/entity/GroupMember.java
backend/src/main/java/backend/hanpum/domain/group/repository/GroupMemberRepository.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupMemberRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupMemberRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java
backend/src/main/java/backend/hanpum/exception/exception/group/GroupMemberFullException.java
backend/src/main/java/backend/hanpum/exception/exception/group/GroupPermissionException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- 모임 신청 코드 개선
- 모임 신청 리스트 조회 API 코드 작성
- 모임 신청 수락 API 코드 작성
- 모임 신청 거절 API 코드 작성

[BE] 모임 신청 관리 API

---

backend/src/main/java/backend/hanpum/domain/group/controller/GroupController.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupDetailGetResDto.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupResDto.java
backend/src/main/java/backend/hanpum/domain/group/entity/Group.java
backend/src/main/java/backend/hanpum/domain/group/entity/LikeGroup.java
backend/src/main/java/backend/hanpum/domain/group/repository/LikeGroupRepository.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 관심목록 등록 API 코드 작성
- 모임 리스트/상세 조회 Response에 관심모임 카운트값 추가

[BE] 관심 모임 등록 API

---

frontend/src/components/Meet/MajorTour.tsx
frontend/src/components/Meet/MeetInfo.tsx
frontend/src/components/Meet/MeetSchedule.tsx
frontend/src/components/Meet/MeetScheduleItem.tsx
frontend/src/components/Meet/Member.tsx
frontend/src/components/Style/Meet/MeetInfo.styled.tsx
frontend/src/components/Style/Schedule/AddSchdulePage.styled.tsx
frontend/src/components/Style/Schedule/SchduleMainPage.styled.tsx
frontend/src/pages/Meet/MeetDetailPage.tsx
frontend/src/pages/Schedule/ScheduleMainPage.tsx

- 일정 메인 페이지 추가 & 더미데이터 추가
- MeetInfo, MeetSchedule, MajourTour, Member 컴포넌트에 더미테이터 추가

[FE]일정 메인 페이지 추가 & 더미데이터 추가

---

frontend/src/pages/Schedule/ScheduleMainPage.tsx

[FE] add props schedule main header

---

backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/controller/MemberController.java
backend/src/main/java/backend/hanpum/domain/member/dto/requestDto/UpdatePasswordReqDto.java
backend/src/main/java/backend/hanpum/domain/member/dto/responseDto/MemberProfileResDto.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberService.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 회원 프로필 정보 수정 API 코드 작성
- 회원 비밀번호 수정 API 코드 작성
- 회원 관심 모임 리스트 조회 API 코드 작성

[BE] 회원 마이페이지 API

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java

- [v] 코드 개선
- 경로검색 API 키워드검색 추가
- 경로검색 API 필터조건 추가

[BE] 경로목록조회 API 키워드/필터 검색 추가

---

backend/src/main/java/backend/hanpum/domain/course/repository/custom/CourseRepositoryImpl.java

- [v] 코드 개선
- 경로상세조회시 평점/리뷰수 추가

[BE] 경로상세조회시 평점/리뷰수 추가

---

backend/src/main/java/backend/hanpum/domain/course/entity/CourseUsageHistory.java
backend/src/main/java/backend/hanpum/domain/course/repository/CourseUsageHistoryRepository.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java

- [v] 코드 개선
- 사용한 경로 entity 생성
- 사용한 경로 add api 생성
- 사용한 경로 update api 생성

[BE] 사용한 경로 API 생성

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/SearchAttractionReqDto.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/exception/common/JsonBadMappingException.java
backend/src/main/java/backend/hanpum/exception/exception/common/JsonBadProcessingException.java
backend/src/main/java/backend/hanpum/exception/exception/common/UriBadSyntaxException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- [v] 코드 개선
- 경로 생성 시 사용하는, 관광지 검색 API 생성

[BE] 관광지검색(한국관광공사 Tour api) 통신 API 생성

---

backend/build.gradle
backend/src/main/java/backend/hanpum/config/s3/S3Config.java
backend/src/main/java/backend/hanpum/config/s3/S3ImageService.java
backend/src/main/java/backend/hanpum/domain/auth/controller/AuthController.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/SignUpReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthService.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java
backend/src/main/java/backend/hanpum/domain/member/controller/MemberController.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberService.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberServiceImpl.java
backend/src/main/java/backend/hanpum/exception/exception/s3/FileDeleteFailedException.java
backend/src/main/java/backend/hanpum/exception/exception/s3/FileFormatUnsupportedException.java
backend/src/main/java/backend/hanpum/exception/exception/s3/FilePutFailedException.java
backend/src/main/java/backend/hanpum/exception/format/response/ErrorCode.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java
backend/src/main/java/backend/hanpum/exception/handler/GlobalExceptionHandler.java

- AWS S3 이미지 업로드/삭제 서비스 코드 작성
- 회원가입 프로필 이미지 업로드 코드 작성
- 프로필 이미지 변경 API 코드 작성

[BE] 프로필 이미지 업로드 기능 추가

---

backend/src/main/java/backend/hanpum/domain/group/controller/GroupController.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupMemberListGetResDto.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupMemberResDto.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupMemberRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupMemberRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 모임 가입 멤버 리스트 조회 API 코드 작성
- 모임 가입 멤버 추방 API 코드 작성

[BE] 모임 가입 멤버 조회/추방 API

---

frontend/src/components/Style/Common/Feed.tsx
frontend/src/components/Style/Common/FeedInfo.tsx
frontend/src/components/Style/Route/RouteDetailPage.styled.tsx
frontend/src/models/route.ts
frontend/src/pages/Schedule/ScheduleMainPage.tsx

- 모임 & 경로 & 일정에 들어가는 공통 ui 컴포넌트화했어요 ~ (Feed 처럼 생긴거)

[FE] : 공통 코드 컴포넌트화(Feed)

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/SearchWaypointReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/SearchWaypointResDto.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- [v] 코드 개선
- 카카오 디벨로퍼 장소검색 REST API 통신

[BE] 경유지검색(카카오 developers api) 통신 api 생성

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/MultiWaypointSearchReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/MultiWaypointSearchResDto.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

[BE] 다중경유지 경로 검색(카카오 디벨로퍼 api) 통신

---

backend/build.gradle
backend/src/main/java/backend/hanpum/config/SecurityConfig.java
backend/src/main/java/backend/hanpum/config/jwt/JwtProvider.java
backend/src/main/java/backend/hanpum/config/jwt/UserDetailsImpl.java
backend/src/main/java/backend/hanpum/config/jwt/UserDetailsServiceImpl.java
backend/src/main/java/backend/hanpum/domain/auth/controller/AuthController.java
backend/src/main/java/backend/hanpum/domain/auth/dto/requestDto/KakaoSignUpCompleteReqDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/responseDto/LoginResDto.java
backend/src/main/java/backend/hanpum/domain/auth/dto/responseDto/TokenResDto.java
backend/src/main/java/backend/hanpum/domain/auth/handler/OAuth2SuccessHandler.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthService.java
backend/src/main/java/backend/hanpum/domain/auth/service/AuthServiceImpl.java
backend/src/main/java/backend/hanpum/domain/auth/service/CustomOAuth2UserService.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/domain/member/enums/MemberType.java
backend/src/main/java/backend/hanpum/domain/member/repository/MemberRepository.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 토큰 발급 로직 일부 수정
- 카카오 로그인 구현
- 카카오 회원가입 완료 API 코드 작성
- 멤버 엔티티 수정

[BE] 카카오 로그인/회원가입 구현

---

backend/src/main/java/backend/hanpum/config/jwt/JwtProvider.java
backend/src/main/java/backend/hanpum/domain/member/dto/requestDto/UpdateMemberInfoReqDto.java
backend/src/main/java/backend/hanpum/domain/member/entity/Member.java
backend/src/main/java/backend/hanpum/domain/member/service/MemberServiceImpl.java

- 유저 정보 개별적으로 수정 가능하도록 변경
- 요청 헤더에서 토큰 추출 로직 에러 수정

[BE] 토큰 추출 로직 수정 및 유저 정보 수정 세분화

---

backend/src/main/java/backend/hanpum/domain/course/controller/CourseController.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/AttractionReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/requestDto/WayPointReqDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/AttractionResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/SearchWaypointResDto.java
backend/src/main/java/backend/hanpum/domain/course/dto/responseDto/WayPointResDto.java
backend/src/main/java/backend/hanpum/domain/course/entity/Attraction.java
backend/src/main/java/backend/hanpum/domain/course/entity/Course.java
backend/src/main/java/backend/hanpum/domain/course/entity/Waypoint.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseService.java
backend/src/main/java/backend/hanpum/domain/course/service/CourseServiceImpl.java

- [v] 코드 개선
- 경유지 검색 10개 반환으로 변경
- Float 변수 -> Double 수정 
- 출발지,도착지 주소정보 지역으로 매핑
- S3 이미지로직 추가
- 코스 엔티티 전체일차 컬럼 추가

[BE] 요구사항들 수정

---

backend/src/main/java/backend/hanpum/domain/group/controller/GroupController.java
backend/src/main/java/backend/hanpum/domain/group/dto/requestDto/GroupPostReqDto.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupResDto.java
backend/src/main/java/backend/hanpum/domain/group/entity/Group.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java
backend/src/main/java/backend/hanpum/exception/format/response/ResponseCode.java

- 모임 탈퇴 API 코드 작성
- 모임 리스트 조회 리턴값 수정
- 모임 생성 시 이미지 업로드 기능 추가

[BE] 모임 탈퇴 API 및 모임 생성,조회 수정

---

frontend/src/components/Style/Route/RouteDetailPage.styled.tsx
frontend/src/pages/Router.tsx
frontend/src/pages/index.tsx

[FE] prettier 에러 해결

---

backend/src/main/java/backend/hanpum/domain/group/controller/GroupController.java
backend/src/main/java/backend/hanpum/domain/group/dto/responseDto/GroupListGetResDto.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupRepositoryCustom.java
backend/src/main/java/backend/hanpum/domain/group/repository/custom/GroupRepositoryImpl.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupService.java
backend/src/main/java/backend/hanpum/domain/group/service/GroupServiceImpl.java

- 모임 리스트 조회 정렬 추가 (현재는 인기순, 최신순 2가지만 구현 추후 추가 예정)
- 모임 리스트 조회 페이지네이션 추가

[BE] 모임 리스트 조회 정렬,페이지네이션 추가

---

README.md

- 해당 PR에 작업 내용을 항목으로 자세하게 설명해주세요
- readMe 추가

[FE] Merge: ReadMe 추가
